import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toast";
import { Header } from "@/components/ui/header";
import { HeaderContent } from "@/components/header-content";
import Providers from "@/providers";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Movie Search App",
  description: "Generated by Younes Mousavi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className="relative flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4 pt-[100px]">
            <Header>
              <HeaderContent />
            </Header>
            {children}
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
